allowBuilds:
  '@swc/core': true
  esbuild: true
  mongodb-memory-server: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@payloadcms/db-mongodb@4.0.0-canary.36'
  - '@payloadcms/drizzle@4.0.0-canary.36'
  - '@payloadcms/graphql@4.0.0-canary.36'
  - '@payloadcms/next@4.0.0-canary.36'
  - '@payloadcms/richtext-lexical@4.0.0-canary.36'
  - '@payloadcms/translations@4.0.0-canary.36'
  - '@payloadcms/ui@4.0.0-canary.36'
  - payload@4.0.0-canary.36
